// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.44
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VeselinMarinovVirus
{
    internal sealed partial class Vsix
    {
        public const string Id = "VeselinMarinovVirus.797811e2-dee2-4453-ae0b-623d54820c39";
        public const string Name = "VeselinMarinovVirus";
        public const string Description = @"Gravity logic in visual studio. ";
        public const string Language = "ru-RU";
        public const string Version = "420.69";
        public const string Author = "BangyozFan42";
        public const string Tags = "";
        public const bool IsPreview = false;
    }
}
